language: ruby
rvm:
  - 2.6

env:
  - JEKYLL_ENV=production

script:
  - bundle install
  - travis_wait 40 bundle exec jekyll build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: _site/
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
