language: ruby
rvm:
  - 2.6

env:
  - JEKYLL_ENV=production

services:
  - docker

addons:
  apt:
    packages:
      - raptor2-utils

before_install:
  - docker run -p 3030:3030 -v $PWD/_data/:/staging -d stain/jena-fuseki /jena-fuseki/fuseki-server --file=/staging/heb_inventory.ttl /openhebrew
  - pip3 install rdflib
  
script:
  - bundle install
  - travis_wait 40 bundle exec jekyll build
  - cd _site/
  - ../provisioning/extract.py --file ../_data/heb_inventory.ttl --base "http://mmoon.org/lang/heb/"
  - cd ../../schema/oh/
  - for res in *.ttl; do echo $res; rapper -i turtle -o json $res > ${res%.ttl}.json ; done
  - cd inventory/oh/
  - for res in *.ttl; do echo $res; rapper -i turtle -o json $res > ${res%.ttl}.json ; done

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: _site/
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
