language: ruby
rvm:
  - 2.6

sudo: required

env:
  - JEKYLL_ENV=production

services:
  - docker

addons:
  apt:
    packages:
      - raptor2-utils
      - python3-pip

before_install:
  - docker run -p 3030:3030 -v $PWD/_data/:/staging -d stain/jena-fuseki /jena-fuseki/fuseki-server --file=/staging/heb_inventory.ttl /openhebrew
  - sudo pip3 install rdflib

script:
  - bundle install
  #- travis_wait 40 bundle exec jekyll build
  - mkdir _site
  - cd _site/
  - ../provisioning/createRdfFiles.sh
  - exit 1

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: _site/
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
