# Site settings
title: Open Hebrew
email:
description: ""
baseurl: "/lang/heb/inventory/oh"
url: "http://mmoon.org"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

# Build settings
#theme: minima
plugins:
  - jekyll-rdf
exclude:
  - Gemfile
  - Gemfile.lock
jekyll_rdf:
    path: "_data/heb_inventory.ttl"
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o ; a <http://mmoon.org/lang/heb/schema/oh/Lexeme> . FILTER regex(str(?resourceUri), \"http://mmoon.org/lang/heb/inventory/oh\") }"
    class_template_mappings:
        "http://mmoon.org/lang/heb/schema/oh/Lexeme" : "lexeme.html"
