# Site settings
title: Open Hebrew
email:
description: ""
baseurl: "/JekyllPage"
url: "https://mmoon-project.github.io"
pingback_to: "http://pingback.feedback.aksw.org/"
pingback_service: "http://pingback.feedback.aksw.org/"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

# Build settings
#theme: minima
plugins:
  - jekyll-rdf
exclude:
  - Gemfile
  - Gemfile.lock
  - provisioning
jekyll_rdf:
    baseiri: "http://mmoon.org/lang/heb"
    #path: "_data/heb_inventory.ttl"
    remote:
      endpoint: http://localhost:3030/openhebrew/query
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . { ?resourceUri a <http://mmoon.org/lang/heb/schema/oh/Lexeme> } UNION { ?resourceUri a <http://mmoon.org/lang/heb/schema/oh/PrimaryRoot> } UNION { ?resourceUri a <http://mmoon.org/lang/heb/schema/oh/Binyan> } UNION { ?resourceUri a <http://mmoon.org/mmoon/core/Word> } FILTER regex(str(?resourceUri), \"http://mmoon.org/lang/heb/\") }"
    class_template_mappings:
        "http://mmoon.org/lang/heb/schema/oh/Lexeme" : "lexeme"
        "http://mmoon.org/lang/heb/schema/oh/Root" : "root"
        "http://mmoon.org/lang/heb/schema/oh/Binyan" : "binyan"
        "http://mmoon.org/mmoon/core/Word" : "word"
