# Site settings
title: Open Hebrew
email:
description: ""
baseurl: "/MMoOn-JekyllPage"
url: "http://mmoon.org"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

# Build settings
#theme: minima
plugins:
  - jekyll-rdf
exclude:
  - Gemfile
  - Gemfile.lock
jekyll_rdf:
    baseiri: "http://mmoon.org/lang/heb/inventory/oh"
    #path: "_data/heb_inventory.ttl"
    remote:
      endpoint: http://localhost:3030/openhebrew/query
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . { ?resourceUri a <http://mmoon.org/lang/heb/schema/oh/Lexeme> } UNION { ?resourceUri a <http://mmoon.org/lang/heb/schema/oh/PrimaryRoot> } FILTER regex(str(?resourceUri), \"http://mmoon.org/lang/heb/inventory/oh\") }"
    class_template_mappings:
        "http://mmoon.org/lang/heb/schema/oh/Lexeme" : "lexeme"
        "http://mmoon.org/lang/heb/schema/oh/Root" : "root"
